version: '3.3'
volumes:
  vol-dist-data: {}
networks:
  net-proxy:
    driver: overlay
services:
  vue-app:
    image: jest10820/vue-frontend 
    volumes:
      - vol-dist-data:/home/node/app
    environment:
      - NODE_ENV=production
  nginx:
    image: jest10820/nginx
    ports:
      - "8080:80"
    volumes:
      - vol-dist-data:/app
